[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "https://www.lightofcrete.com/*"
  to = "https://lightofcrete.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/gallery/"
  to = "https://light-of-crete-gallery-demo.netlify.app/gallery/"
  status = 200
  force = true

[[redirects]]
  from = "/gallery"
  to = "/gallery/"
  status = 301
  force = true

[[redirects]]
  from = "/gallery/*"
  to = "https://light-of-crete-gallery-demo.netlify.app/gallery/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
